### Pandas Method Task

In [1]:
# Allowed methods only:
#pd.DataFrame(), pd.read_csv(), head(), tail(), sample(), info(), isnull(), isna(), select_dtypes(),
#describe(), drop(), duplicated(), drop_duplicates(), value_counts(), rename(), add_prefix(),
#astype(), fillna(), mean(), median()

### Easy Level (1–10)

In [10]:
# Q1 Load the dataset and display the first 10 records.

import pandas as pd
df = pd.read_excel("C:\\Users\\DELL\\Downloads\\Bank_customer_churn.xlsx")

In [12]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [13]:
# Q2 Display the last 15 customers.

df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [14]:
# Q3 Show 7 random customer records.

df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5327,5328,15641490,Windsor,850,Germany,Female,25,8,69385.17,2,1,0,87834.24,0
6337,6338,15618243,Buckland,730,Spain,Female,43,1,103960.38,1,1,1,193650.16,0
5823,5824,15573628,Greene,751,Germany,Female,51,7,148074.79,1,1,0,146411.41,1
4059,4060,15691952,Fanucci,676,France,Male,37,10,106242.67,1,1,1,166678.28,0
1177,1178,15651369,Wright,626,France,Male,21,1,0.00,2,1,0,66232.23,0
119,120,15600781,Wu,699,Germany,Male,34,4,185173.81,2,1,0,120834.48,0
7598,7599,15613699,Schnaars,430,France,Female,60,7,73937.02,1,1,0,161937.62,1

In [20]:
# Q4 Print complete dataset information and identify:
#• Total columns
#• Data type of each column
#• Missing values

df.info()
df.shape[1]
df.dtypes
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [23]:
# Q5 Find missing values in every column.

df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [32]:
# Q6 Display only numerical columns.

df.select_dtypes(include=["number"])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

In [33]:
# Q7 Generate the statistical summary of numerical columns.

df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [34]:
# Q8 Find duplicate rows and print how many exist.

df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [38]:
# Q9 Remove duplicate rows and store the cleaned dataset.

cleaned_df = df.drop_duplicates()
print(cleaned_df.shape)

(10000, 14)

In [39]:
# Q10 Count how many customers have exited and how many have not exited.

df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

### Medium Level (11–20)

In [42]:
# Q11Rename the following columns:
#CustomerId → Customer_ID
#CreditScore → Credit_Score
#EstimatedSalary → Salary
#Exited → Churn

df.rename(columns = {"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary","Exited":"Churn"},inplace= True)
df.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'Salary', 'Churn'],
      dtype='object')

In [46]:
# Q12 Add the prefix Bank_ to every column name.

df.add_prefix("Bank_")

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [47]:
# Q13 Convert the Age column into float datatype.

df["Age"].astype(float)

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Age, Length: 10000, dtype: float64

In [52]:
# Q14 Convert the Exited column into string datatype.

df["Churn"].astype(str)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Churn, Length: 10000, dtype: object

In [53]:
# Q15 Suppose the Balance column has missing values. Replace them using the mean of the Balance column.

mean_balance=df["Balance"].mean()
df["Balance"]=df["Balance"].fillna(mean_balance)
df["Balance"].isnull().sum()

np.int64(0)

In [54]:
# Q16 Suppose the Age column has missing values. Replace them using the median age.

median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)
df["Age"].isnull().sum()

np.int64(0)

In [55]:
# Q17 Display only the first five rows after renaming the columns.

df.head(5)

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [59]:
# Q18 Create a new DataFrame by dropping these columns:
#RowNumber
#CustomerId
#Surname
#Display the first 10 rows.

new_df=df.drop(columns=["RowNumber","Customer_ID","Surname"])
new_df.head(10)

,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [68]:
# Q19 Drop the Geography column and display dataset information again.

df = df.drop("Geography", axis=1, errors="ignore")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   RowNumber       10000 non-null  int64
 1   Customer_ID     10000 non-null  int64
 2   Surname         10000 non-null  object
 3   Credit_Score    10000 non-null  int64
 4   Gender          10000 non-null  object
 5   Age             10000 non-null  int64
 6   Tenure          10000 non-null  int64
 7   Balance         10000 non-null  float64
 8   NumOfProducts   10000 non-null  int64
 9   HasCrCard       10000 non-null  int64
 10  IsActiveMember  10000 non-null  int64
 11  Salary          10000 non-null  float64
 12  Churn           10000 non-null  int64
dtypes: float64(2), int64(9), object(2)
memory usage: 1015.8+ KB

In [72]:
# Q20 Rename NumOfProducts to Products and HasCrCard to CreditCard.

df.rename(columns={"NumOfProducts":"Products","HasCrCard":"CreditCard"},inplace= True)
df.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Gender', 'Age',
       'Tenure', 'Balance', 'Products', 'CreditCard', 'IsActiveMember',
       'Salary', 'Churn'],
      dtype='object')

### Hard Level (21–30)

In [73]:
# Q21 (Real Company Task) Your manager wants cleaner column names.
#Rename every column as follows:
#RowNumber → Row_No
#CustomerId → Customer_ID
#Surname → Last_Name
#CreditScore → Credit_Score
#Geography → Country
#Gender → Sex
#EstimatedSalary → Salary
#Exited → Target
#Display the first five rows.

df.rename(columns={"RowNumber":"Row_No","CustomerId":"Customer_ID","Surname":"Last_Name","CreditScore":"Credit_Score",
                   "Geography":"Country","Gender":"Sex","EstimatedSalary":"Salary","Exited":"Target"},inplace=True)
df.columns

Index(['Row_No', 'Customer_ID', 'Last_Name', 'Credit_Score', 'Sex', 'Age',
       'Tenure', 'Balance', 'Products', 'CreditCard', 'IsActiveMember',
       'Salary', 'Churn'],
      dtype='object')

In [76]:
# Q22 Create a new DataFrame that contains only numeric columns. Then generate its statistical summary.

numeric_df=df.select_dtypes(include=['number'])
numeric_df
numeric_df.describe()

,Row_No,Customer_ID,Credit_Score,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Churn
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [77]:
# Q23 Your company received duplicate customer records.
#Tasks:
#• Count duplicates.
#• Remove duplicates.
#• Display dataset information after cleaning.

df.duplicated().sum()
df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_No          10000 non-null  int64
 1   Customer_ID     10000 non-null  int64
 2   Last_Name       10000 non-null  object
 3   Credit_Score    10000 non-null  int64
 4   Sex             10000 non-null  object
 5   Age             10000 non-null  int64
 6   Tenure          10000 non-null  int64
 7   Balance         10000 non-null  float64
 8   Products        10000 non-null  int64
 9   CreditCard      10000 non-null  int64
 10  IsActiveMember  10000 non-null  int64
 11  Salary          10000 non-null  float64
 12  Churn           10000 non-null  int64
dtypes: float64(2), int64(9), object(2)
memory usage: 1015.8+ KB

In [78]:
# Q24
#Management wants every column name to begin with Customer_
#Apply this transformation using the appropriate method.

df.add_prefix("Customer_")

,Customer_Row_No,Customer_Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Sex,Customer_Age,Customer_Tenure,Customer_Balance,Customer_Products,Customer_CreditCard,Customer_IsActiveMember,Customer_Salary,Customer_Churn
0,1,15634602,Hargrave,619,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28,4,130142.79,1,1,0,38190.78,0

In [83]:
# Q25 After renaming the columns, convert
#Age
#Balance
#Salary
#to float datatype.
#Print dataset information.

df["Age"].astype(float)
df["Salary"].astype(float)
df["Balance"].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_No          10000 non-null  int64
 1   Customer_ID     10000 non-null  int64
 2   Last_Name       10000 non-null  object
 3   Credit_Score    10000 non-null  int64
 4   Sex             10000 non-null  object
 5   Age             10000 non-null  int64
 6   Tenure          10000 non-null  int64
 7   Balance         10000 non-null  float64
 8   Products        10000 non-null  int64
 9   CreditCard      10000 non-null  int64
 10  IsActiveMember  10000 non-null  int64
 11  Salary          10000 non-null  float64
 12  Churn           10000 non-null  int64
dtypes: float64(2), int64(9), object(2)
memory usage: 1015.8+ KB

In [86]:
# Q26 Assume CreditScore contains missing values. Replace them with the median CreditScore.

median_score = df["Credit_Score"].median()
df["Credit_Score"] = df["Credit_Score"].fillna(median_score)
df["Credit_Score"].isnull().sum()

np.int64(0)

In [87]:
# Q27 Assume EstimatedSalary contains missing values. Replace them with the mean salary. Then print the first eight rows.

mean_salary = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna(mean_salary)
df.head(8)

,Row_No,Customer_ID,Last_Name,Credit_Score,Sex,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Female,29,4,115046.74,4,1,0,119346.88,1

In [93]:
# Q28 (Data Cleaning Challenge)
#Perform all the following:
#• Remove duplicate rows.
#• Rename Exited to Target.
#• Convert Target to string.
#• Display dataset information.

df.drop_duplicates(inplace=True)
df.rename(columns = {"Churn":"Target"},inplace= True)
df["Target"]=df["Target"].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_No          10000 non-null  int64
 1   Customer_ID     10000 non-null  int64
 2   Last_Name       10000 non-null  object
 3   Credit_Score    10000 non-null  int64
 4   Sex             10000 non-null  object
 5   Age             10000 non-null  int64
 6   Tenure          10000 non-null  int64
 7   Balance         10000 non-null  float64
 8   Products        10000 non-null  int64
 9   CreditCard      10000 non-null  int64
 10  IsActiveMember  10000 non-null  int64
 11  Salary          10000 non-null  float64
 12  Target          10000 non-null  object
dtypes: float64(2), int64(8), object(3)
memory usage: 1015.8+ KB

In [97]:
# Q29 (Transformation Challenge)
#Create a copy of the dataset.
#Perform these transformations:
#• Rename Gender to CustomerGender
#• Rename Geography to Country
#• Add prefix Bank_
#• Remove RowNumber
#• Display first 10 rows

df_copy=df.copy()
df_copy.rename(columns={"Gender":"CustomerGender","Geography":"Country"},inplace = True)
df_copy.add_prefix("Bank_")
df_copy.drop("Bank_RowNumber",axis=1,inplace=True,errors="ignore")
df_copy.head(10)

,Row_No,Customer_ID,Last_Name,Credit_Score,Sex,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,Male,27,2,134603.88,1,1,1,71725.73,0

In [98]:
# Q30 Real Industry Mini Project
#Your manager asks you to prepare a cleaned dataset for the Machine Learning team.
#Perform all of these steps:
#1. Load the dataset.
#2. Display dataset information.
#3. Check missing values.
#4. Remove duplicate rows.
#5. Rename the following columns:
#o CustomerId → Customer_ID
#o CreditScore → Credit_Score
#o EstimatedSalary → Salary
#o Exited → Target
#6. Convert:
#o Age → float
#o Balance → float
# Target → string
#7. Replace missing values:
#o Age → median
#o Balance → mean
#8. Remove:
#o RowNumber
#o Surname
#9. Display:
#o First 10 rows
#o Statistical summary
#o Value counts of Target
#o Final dataset information

import pandas as pd


df = pd.read_excel(r"C:\Users\DELL\Downloads\Bank_customer_churn.xlsx")

print("========== Dataset Information ==========")
df.info()


print("\n========== Missing Values ==========")
print(df.isnull().sum())


df.drop_duplicates(inplace=True)

df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Target"
}, inplace=True)


df["Age"] = df["Age"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)


df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

df.drop(columns=["RowNumber", "Surname"], inplace=True)


print("\n========== First 10 Rows ==========")
print(df.head(10))

print("\n========== Statistical Summary ==========")
print(df.describe())

print("\n========== Target Value Counts ==========")
print(df["Target"].value_counts())

print("\n========== Final Dataset Information ==========")
df.info()

========== Dataset Information ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

========== Missing Values ==========
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

========== First 10 Rows ==========
   Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82
5     15574012           645     Spain    Male  44.0       8  113755.78
6     15592531           822    France    Male  50.0       7       0.00
7     15656148           376   Germany  Female  29.0       4  115046.74
8     15792365           501    France    Male  44.0       4  142051.07
9     15592389           684    France    Male  27.0       2  134603.88

   NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0              1          1               1  101348.88      1
1              1          0               1  112542.58      0
2              3          1               0  113931.57      1
3              2          0               0   93826.63      0
4              1          1               1   79084.10      0
5              2          1               0  149756.71      1
6              2          1               1   10062.80      0
7              4          1               0  119346.88      1
8              2          0               1   74940.50      0
9              1          1               1   71725.73      0

========== Statistical Summary ==========
        Customer_ID  Credit_Score           Age        Tenure        Balance  \
count  1.000000e+04  10000.000000  10000.000000  10000.000000   10000.000000
mean   1.569094e+07    650.528800     38.921800      5.012800   76485.889288
std    7.193619e+04     96.653299     10.487806      2.892174   62397.405202
min    1.556570e+07    350.000000     18.000000      0.000000       0.000000
25%    1.562853e+07    584.000000     32.000000      3.000000       0.000000
50%    1.569074e+07    652.000000     37.000000      5.000000   97198.540000
75%    1.575323e+07    718.000000     44.000000      7.000000  127644.240000
max    1.581569e+07    850.000000     92.000000     10.000000  250898.090000

       NumOfProducts    HasCrCard  IsActiveMember         Salary
count   10000.000000  10000.00000    10000.000000   10000.000000
mean        1.530200      0.70550        0.515100  100090.239881
std         0.581654      0.45584        0.499797   57510.492818
min         1.000000      0.00000        0.000000      11.580000
25%         1.000000      0.00000        0.000000   51002.110000
50%         1.000000      1.00000        1.000000  100193.915000
75%         2.000000      1.00000        1.000000  149388.247500
max         4.000000      1.00000        1.000000  199992.480000

========== Target Value Counts ==========
Target
0    7963
1    2037
Name: count, dtype: int64

========== Final Dataset Information ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     10000 non-null  int64
 1   Credit_Score    10000 non-null  int64
 2   Geography       10000 non-null  object
 3   Gender          10000 non-null  object
 4   Age             10000 non-null  float64
 5   Tenure          10000 non-null  int64
 6   Balance         10000 non-null  float64
 7   NumOfProducts   10000 non-null  int64
 8   HasCrCard       10000 non-null  int64
 9   IsActiveMember  10000 non-null  int64
 10  Salary          10000 non-null  float64
 11  Target          10000 non-null  object
dtypes: float64(3), int64(6), object(3)
memory usage: 937.6+ KB

In [99]:
# Bonus Challenge (Create New Columns)
#These require creating new columns using basic Pandas assignment along with the methods you've learned.
#B1
#Create a new column:
#TotalMoney = Balance + EstimatedSalary


df["TotalMoney"] = df["Balance"] + df["Salary"]
print(df.head())

   Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82

   NumOfProducts  HasCrCard  IsActiveMember     Salary Target  TotalMoney
0              1          1               1  101348.88      1   101348.88
1              1          0               1  112542.58      0   196350.44
2              3          1               0  113931.57      1   273592.37
3              2          0               0   93826.63      0    93826.63
4              1          1               1   79084.10      0   204594.92

In [100]:
#B2 Create a new column:
#DoubleScore = CreditScore × 2


df["DoubleScore"] = df["Credit_Score"] * 2
print(df.head())

   Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82

   NumOfProducts  HasCrCard  IsActiveMember     Salary Target  TotalMoney  \
0              1          1               1  101348.88      1   101348.88
1              1          0               1  112542.58      0   196350.44
2              3          1               0  113931.57      1   273592.37
3              2          0               0   93826.63      0    93826.63
4              1          1               1   79084.10      0   204594.92

   DoubleScore
0         1238
1         1216
2         1004
3         1398
4         1700

In [101]:
#B3 Create a new column:
#AgeAfter10Years = Age + 10


df["AgeAfter10Years"] = df["Age"] + 10
print(df.head())

   Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82

   NumOfProducts  HasCrCard  IsActiveMember     Salary Target  TotalMoney  \
0              1          1               1  101348.88      1   101348.88
1              1          0               1  112542.58      0   196350.44
2              3          1               0  113931.57      1   273592.37
3              2          0               0   93826.63      0    93826.63
4              1          1               1   79084.10      0   204594.92

   DoubleScore  AgeAfter10Years
0         1238             52.0
1         1216             51.0
2         1004             52.0
3         1398             49.0
4         1700             53.0

In [102]:
#B4 Create a new column:
#HasBalance = Balance
#Replace missing values in this new column using the mean.


df["HasBalance"] = df["Balance"]
mean_balance = df["HasBalance"].mean()
df["HasBalance"] = df["HasBalance"].fillna(mean_balance)
print(df.head())

   Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82

   NumOfProducts  HasCrCard  IsActiveMember     Salary Target  TotalMoney  \
0              1          1               1  101348.88      1   101348.88
1              1          0               1  112542.58      0   196350.44
2              3          1               0  113931.57      1   273592.37
3              2          0               0   93826.63      0    93826.63
4              1          1               1   79084.10      0   204594.92

   DoubleScore  AgeAfter10Years  HasBalance
0         1238             52.0        0.00
1         1216             51.0    83807.86
2         1004             52.0   159660.80
3         1398             49.0        0.00
4         1700             53.0   125510.82

In [103]:
#B5 Create a new column:
#SalaryInLakhs = EstimatedSalary / 100000


df["SalaryInLakhs"] = df["Salary"] / 100000
print(df.head())

   Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82

   NumOfProducts  HasCrCard  IsActiveMember     Salary Target  TotalMoney  \
0              1          1               1  101348.88      1   101348.88
1              1          0               1  112542.58      0   196350.44
2              3          1               0  113931.57      1   273592.37
3              2          0               0   93826.63      0    93826.63
4              1          1               1   79084.10      0   204594.92

   DoubleScore  AgeAfter10Years  HasBalance  SalaryInLakhs
0         1238             52.0        0.00       1.013489
1         1216             51.0    83807.86       1.125426
2         1004             52.0   159660.80       1.139316
3         1398             49.0        0.00       0.938266
4         1700             53.0   125510.82       0.790841