### Flight Price Datasets— 30 Clean Questions

In [3]:
# 1. Load the Flight Price dataset into a Pandas DataFrame and display the first five rows.

import pandas as pd
df = pd.read_csv("C:\\Users\\DELL\\Downloads\\Data_Train.xlsx - Sheet1.csv")
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [5]:
# 2. Find the number of rows and columns in the dataset.

df.shape

(10683, 11)

In [6]:
# 3. Display all column names in the dataset.

df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [9]:
# 4. Display the data types of all columns.

df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [10]:
# 5. Use df.info() to inspect the structure of the dataset.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [11]:
# 6. Check the number of missing values in each column.

df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [15]:
# 7. Check the percentage of missing values in each column.

(df.isnull().sum()/len(df)*100).round(2)

Airline            0.00
Date_of_Journey    0.00
Source             0.00
Destination        0.00
Route              0.01
Dep_Time           0.00
Arrival_Time       0.00
Duration           0.00
Total_Stops        0.01
Additional_Info    0.00
Price              0.00
dtype: float64

In [17]:
df.isnull().mean().round(2)

Airline            0.0
Date_of_Journey    0.0
Source             0.0
Destination        0.0
Route              0.0
Dep_Time           0.0
Arrival_Time       0.0
Duration           0.0
Total_Stops        0.0
Additional_Info    0.0
Price              0.0
dtype: float64

In [18]:
# 8. Display the unique values and frequency of each value in the Airline column.

df["Airline"].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [23]:
# 9. Display the frequency distribution of Total_Stops, including missing values.

(df["Total_Stops"].value_counts(dropna=False))

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
NaN            1
4 stops        1
Name: count, dtype: int64

In [28]:
# 10.Convert Date_of_Journey into a datetime format.

df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format="%d%m%y")

In [31]:
#11.Extract the day from Date_of_Journey and create a day column.

df["day"] = df["Date_of_Journey"].dt.day
df[["Date_of_Journey","day"]].head()

  Date_of_Journey  day
0      2019-03-24   24
1      2019-05-01    1
2      2019-06-09    9
3      2019-05-12   12
4      2019-03-01    1

In [33]:
# 12.Extract the month from Date_of_Journey and create a month column.

df["month"] = df["Date_of_Journey"].dt.month
df[["Date_of_Journey","month"]].head()

  Date_of_Journey  month
0      2019-03-24      3
1      2019-05-01      5
2      2019-06-09      6
3      2019-05-12      5
4      2019-03-01      3

In [38]:
# 13.Extract the year from Date_of_Journey and create a year column.

df["year"] = df["Date_of_Journey"].dt.year
df[["Date_of_Journey","year"]].head()

  Date_of_Journey  year
0      2019-03-24  2019
1      2019-05-01  2019
2      2019-06-09  2019
3      2019-05-12  2019
4      2019-03-01  2019

In [39]:
# 14.Drop the original Date_of_Journey column after extracting the required features.

df.drop("Date_of_Journey",axis=1,inplace=True)

In [47]:
# 15.Convert Dep_Time into datetime format and extract the departure hour into Dep_Hour.

df["Dep_Time"] = pd.to_datetime(df["Dep_Time"],format="%H:%M")
df["Dep_Hour"] = df["Dep_Time"].dt.hour
print(df[["Dep_Time","Dep_Hour"]].head())

             Dep_Time  Dep_Hour
0 1900-01-01 22:20:00        22
1 1900-01-01 05:50:00         5
2 1900-01-01 09:25:00         9
3 1900-01-01 18:05:00        18
4 1900-01-01 16:50:00        16

In [50]:
# 16.Extract the departure minute from Dep_Time and create Dep_Minute.

df["Dep_Minute"] = df["Dep_Time"].dt.minute
df[["Dep_Time","Dep_Hour","Dep_Minute"]].head()

             Dep_Time  Dep_Hour  Dep_Minute
0 1900-01-01 22:20:00        22          20
1 1900-01-01 05:50:00         5          50
2 1900-01-01 09:25:00         9          25
3 1900-01-01 18:05:00        18           5
4 1900-01-01 16:50:00        16          50

In [51]:
# 17.Drop the original Dep_Time column after extracting the required features.

df.drop(columns=["Dep_Time"],inplace=True)

In [53]:
# 18.Extract only the time portion from Arrival_Time.

df["Arrival_Time"] = df["Arrival_Time"].str.split().str[0]
df["Arrival_Time"].head()

0    01:10
1    13:15
2    04:25
3    23:30
4    21:35
Name: Arrival_Time, dtype: object

In [56]:
# 19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.

df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"],format="%H:%M")
df["Arrival_Hour"] = df["Arrival_Time"].dt.hour
df["Arrival_Minute"] = df["Arrival_Time"].dt.minute
df[["Arrival_Time","Arrival_Hour","Arrival_Minute"]].head()

         Arrival_Time  Arrival_Hour  Arrival_Minute
0 1900-01-01 01:10:00             1              10
1 1900-01-01 13:15:00            13              15
2 1900-01-01 04:25:00             4              25
3 1900-01-01 23:30:00            23              30
4 1900-01-01 21:35:00            21              35

In [58]:
# 20.Drop the original Arrival_Time column after extracting the required features.

df.drop(columns=["Arrival_Time"],inplace=True)

In [62]:
# 21.Extract the hour component from Duration and create Duration_Hour. Handle invalid or missing extracted values appropriately.

df["Duration_Hour"] = df["Duration"].str.extract(r"(\d+)h",expand=False)
df["Duration_Hour"] = pd.to_numeric(df["Duration_Hour"],errors = "coerce")

In [63]:
# 22.Extract the minute component from Duration and create Duration_Minute. Handle invalid or missing extracted values appropriately.

df["Duration_Minute"] = pd.to_numeric(df["Duration"].str.extract(r"(\d+)m",expand=False),errors="coerce")

In [65]:
# 23.Drop the original Duration column after creating the numerical duration features.

df.drop(columns=["Duration"],inplace=True)

In [66]:
# 24.Replace non-stop in Total_Stops with 0 stops.

df["Total_Stops"] = df["Total_Stops"].replace("non_stope",0)

In [69]:
# 25.Extract only the numerical value from Total_Stops and convert the column into an integer data type. Handle missing or invalid values appropriately.

df["Total_Stops"] = pd.to_numeric(df["Total_Stops"].astype(str).str.extract(r"(\d+)",expand=False),errors="coerce").fillna(0).astype(int)

In [73]:
# 26.Split the Route column using → as the separator and create Route_1, Route_2, Route_3, Route_4, and Route_5.

df[["Route_1","Route_2","Route_3","Route_4","Route_5"]] = (df["Route"].str.split(" → ",expand=True).reindex(columns=range(5)))
df[["Route","Route_1","Route_2","Route_3","Route_4","Route_5"]].head()

                   Route Route_1 Route_2 Route_3 Route_4 Route_5
0              BLR → DEL     BLR     DEL    None    None    None
1  CCU → IXR → BBI → BLR     CCU     IXR     BBI     BLR    None
2  DEL → LKO → BOM → COK     DEL     LKO     BOM     COK    None
3        CCU → NAG → BLR     CCU     NAG     BLR    None    None
4        BLR → NAG → DEL     BLR     NAG     DEL    None    None

In [75]:
# 27.Identify the missing values created in Route_3, Route_4, and Route_5 after splitting the route.

df[df[["Route_3","Route_4","Route_5"]].isnull().any(axis=1)]

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,dat,day,month,...,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,24,3,...,20,1,10,2.0,50.0,BLR,DEL,None,None,None
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,1,5,...,50,13,15,7.0,25.0,CCU,IXR,BBI,BLR,None
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,9,6,...,25,4,25,19.0,NaN,DEL,LKO,BOM,COK,None
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,12,5,...,5,23,30,5.0,25.0,CCU,NAG,BLR,None,None
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,1,3,...,50,21,35,4.0,45.0,BLR,NAG,DEL,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0,No info,4107,9,9,4,...,55,22,25,2.0,30.0,CCU,BLR,None,None,None
10679,Air India,Kolkata,Banglore,CCU → BLR,0,No info,4145,27,27,4,...,45,23,20,2.0,35.0,CCU,BLR,None,None,None
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0,No info,7229,27,27,4,...,20,11,20,3.0,NaN,BLR,DEL,None,None,None
10681,Vistara,Banglore,New Delhi,BLR → DEL,0,No info,12648,1,1,3,...,30,14,10,2.0,40.0,BLR,DEL,None,None,None
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2,No info,11753,9,9,5,...,55,19,15,8.0,20.0,DEL,GOI,BOM,COK,None

In [78]:
# 28.Replace the missing values in the route columns with an appropriate value such as None.

df[["Route_1","Route_2","Route_3","Route_4","Route_5"]] = (df[["Route_1","Route_2","Route_3","Route_4","Route_5"]].fillna("None"))

In [79]:
# 29.Drop the original Route column after creating and cleaning the route features.

df.drop(columns=["Route"],inplace=True)

In [81]:
# 30.After completing all data cleaning and feature engineering, separate the
#dataset into X (independent variables) and y (target variable), where Price
#is the target.

X = df.drop("Price",axis=1)
y = df["Price"]
X.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,dat,day,month,year,dep_Hour,...,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5
0,IndiGo,Banglore,New Delhi,0,No info,24,24,3,2019,22,...,20,1,10,2.0,50.0,BLR,DEL,None,None,None
1,Air India,Kolkata,Banglore,2,No info,1,1,5,2019,5,...,50,13,15,7.0,25.0,CCU,IXR,BBI,BLR,None
2,Jet Airways,Delhi,Cochin,2,No info,9,9,6,2019,9,...,25,4,25,19.0,NaN,DEL,LKO,BOM,COK,None
3,IndiGo,Kolkata,Banglore,1,No info,12,12,5,2019,18,...,5,23,30,5.0,25.0,CCU,NAG,BLR,None,None
4,IndiGo,Banglore,New Delhi,1,No info,1,1,3,2019,16,...,50,21,35,4.0,45.0,BLR,NAG,DEL,None,None

In [82]:
y.head()

0     3897
1     7662
2    13882
3     6218
4    13302
Name: Price, dtype: int64