### Pandas Challenges (Based on Your Notebook)

In [1]:
# Challenge 1 – Complete Data Cleaning
#Your manager gives you a messy dataset.
#Perform all of the following:
#• Load the dataset.
#• Display dataset information.
#• Find missing values.
#• Remove duplicate rows.
#• Fill missing values:
#o Age → median
#o Balance → mean
#• Rename:
#o Target → CustomerStatus
#o AnnualIncome → Income
#• Display the first 15 rows.
#Methods expected:
#read_csv()
#info()
#isnull()
#drop_duplicates()
#median()
#mean()
#fillna()
#rename()
#head()

import pandas as pd

df2 = pd.read_csv("C:\\Users\\DELL\\Downloads\\Task_dataset - Task_dataset.csv")

In [2]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [3]:
df2.isnull().sum()

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [4]:
df2.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [8]:
df2["Age"]=df2["Age"].fillna(df2["Age"].median())
df2.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn

In [9]:
df2["Balance"]=df2["Balance"].fillna(df2["Balance"].mean())
df2.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

In [13]:
# Reaname
df2 = df2.rename(columns={"Target":"CustomerStatus","AnnualIncome":"Income"})
df2

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn

In [15]:
 df2.head(15)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

In [17]:
# Challenge 2 – Banking Report
#The bank wants a numeric report.
#Tasks
#• Select only numeric columns.
#• Display summary statistics.
#• Convert Age and CreditScore to float.
#• Display information again.

df2.select_dtypes(include="number")

      CustomerID   Age    Income  Spending  CreditScore        Balance  Tenure
0          10001  58.0   49184.0      2139          581   97523.535666       2
1          10002  65.0  162964.0      6197          732    6356.540000       1
2          10003  56.0   26956.0     37281          503  143203.920000       8
3          10004  55.0   92926.0       925          463  139627.880000       5
4          10005  66.0  108236.0      7198          394   75985.460000       5
...          ...   ...       ...       ...          ...            ...     ...
1015       10450  43.0  173620.0      7121          644   60353.030000       2
1016       10753  25.0   54490.0     13794          303  124512.070000       4
1017       10810  49.0   82062.0     47170          813   53850.090000       8
1018       10267  38.0       NaN     10424          722  138100.050000       6
1019       10059  62.0   97504.0     36833          430   97523.535666      10

[1020 rows x 7 columns]

In [18]:
df2.describe()

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,967.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,52303.362541,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,66149.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,158000.500000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [24]:
df2["Age"] = df2["Age"].astype(float)
df2["CreditScore"]= df2["CreditScore"].astype(float)
df2

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn

In [25]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1020 non-null   int64
 1   Age             1020 non-null   float64
 2   Income          967 non-null    float64
 3   Spending        1020 non-null   int64
 4   CreditScore     1020 non-null   float64
 5   Balance         1020 non-null   float64
 6   Tenure          1020 non-null   int64
 7   Geography       969 non-null    object
 8   Gender          968 non-null    object
 9   Segment         969 non-null    object
 10  CustomerStatus  1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

In [30]:
# Challenge 3 – Duplicate Investigation
#Find duplicate customers.
#Then
#• Count duplicate rows.
#• Remove duplicates.
#• Print information before and after removing duplicates.
#• Show the last 20 rows.

df2.duplicated().sum()

np.int64(20)

In [31]:
df2.drop_duplicates()

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761.0,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780.0,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733.0,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540.0,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559.0,100908.400000,6,UK,Female,NaN,Stay

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1020 non-null   int64
 1   Age             1020 non-null   float64
 2   Income          967 non-null    float64
 3   Spending        1020 non-null   int64
 4   CreditScore     1020 non-null   float64
 5   Balance         1020 non-null   float64
 6   Tenure          1020 non-null   int64
 7   Geography       969 non-null    object
 8   Gender          968 non-null    object
 9   Segment         969 non-null    object
 10  CustomerStatus  1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

In [33]:
df2.tail(20)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
1000,10643,41.0,125012.0,18825,761.0,35977.850000,2,Germany,Other,Retail,Stay
1001,10763,56.0,102965.0,17517,838.0,115028.540000,9,UK,NaN,SME,Stay
1002,10910,66.0,118506.0,6296,306.0,81892.130000,4,Canada,Male,SME,Churn
1003,10200,19.0,115052.0,20741,484.0,190233.860000,5,Canada,Male,Retail,Churn
1004,10587,29.0,NaN,40255,383.0,168358.600000,2,Germany,Male,Corporate,Churn
1005,10798,22.0,176830.0,7626,688.0,65481.650000,10,France,Male,Retail,Stay
1006,10653,32.0,NaN,21266,598.0,142086.700000,9,France,Female,Corporate,Stay
1007,10756,53.0,74430.0,3705,489.0,29651.230000,10,UK,Male,Retail,Churn
1008,10417,70.0,40417.0,37956,681.0,23880.190000,10,India,Male,Retail,Stay
1009,10499,34.0,166546.0,12497,643.0,130886.930000,3,UK,Male,SME,Stay
1010,10515,62.0,199762.0,41808,309.0,60223.290000,10,India,Other,SME,Churn
1011,10457,44.0,63604.0,27633,804.0,176354.130000,5,Germany,Female,Retail,Stay
1012,10882,61.0,115417.0,3879,413.0,76591.000000,7,NaN,Male,Corporate,Churn
1013,10531,64.0,85162.0,32083,654.0,132742.130000,10,Canada,Male,SME,Stay
1014,10181,50.0,166466.0,44281,662.0,14415.100000,0,Canada,Male,Corporate,Churn
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn

In [34]:
# Challenge 4 – HR Department
#HR wants better column names.
#Rename
#CustomerID → Employee_ID
#Age → EmployeeAge
#Gender → EmployeeGender
#AnnualIncome → Salary
#Target → PromotionStatus
#Then
#• Add prefix
#HR_
#to every column.
#Display 10 random records.

df2.rename(columns={"Age":"Employee_ID","AnnualIncome":"Salary","Target":"PromotionStatus"})

,CustomerID,Employee_ID,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn

In [35]:
df2.add_prefix("HR_")

,HR_CustomerID,HR_Age,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_Gender,HR_Segment,HR_CustomerStatus
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn

In [36]:
df2.sample(10)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
358,10359,27.0,110431.0,2109,794.0,20909.87,6,India,Male,SME,Stay
453,10454,58.0,NaN,7322,808.0,28128.67,1,USA,Female,NaN,Churn
1015,10450,43.0,173620.0,7121,644.0,60353.03,2,USA,Other,Corporate,Stay
896,10897,46.0,88264.0,24726,488.0,41031.07,0,France,Female,Corporate,Churn
439,10440,58.0,162516.0,1779,691.0,156383.15,5,Canada,Other,Corporate,Stay
38,10039,26.0,196079.0,42803,607.0,91444.91,1,India,Female,SME,Churn
370,10371,52.0,189151.0,11853,868.0,33373.10,4,USA,Male,Corporate,Stay
128,10129,43.0,190350.0,5763,636.0,170468.27,8,Canada,Female,SME,Stay
81,10082,31.0,141905.0,46340,562.0,153379.62,2,Germany,NaN,SME,Stay
693,10694,70.0,181725.0,17920,841.0,8130.63,1,UK,Male,Retail,Churn

In [37]:
# Challenge 5 – Finance Cleaning
#Finance department reports missing values.
#Tasks
#Fill
#AnnualIncome → Median
#Balance → Mean
#Age → Median
#Then
#Generate descriptive statistics.

df2 = pd.read_csv("C:\\Users\\DELL\\Downloads\\Task_dataset - Task_dataset.csv")

In [40]:
df2["AnnualIncome"] = df2["AnnualIncome"].fillna(df2["AnnualIncome"].median())

In [41]:
df2["Balance"] = df2["Balance"].fillna(df2["Balance"].mean())

In [43]:
df2["Age"] = df2["Age"].fillna(df2["Age"].median())

In [44]:
df2.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [46]:
# Challenge 6 – Data Type Audit
#The company says
#Age and AnnualIncome are stored incorrectly.
#Tasks
#Convert
#Age → int
#AnnualIncome → float
#Balance → float
#Target → string
#Print information.

df2["Age"] = df2["Age"].astype(int)
df2["AnnualIncome"]=df2["AnnualIncome"].astype(float)
df2["Balance"]=df2["Balance"].astype(float)
df2["Target"]=df2["Target"].astype(str)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB

In [48]:
# Challenge 7 – Customer Analytics
#Create a new DataFrame that
#• removes Segment
#• removes Geography
#• removes duplicate rows
#Display
#• first 10 rows
#• dataset information
#• statistical summary

df2_new = df2.drop(columns=["Segment","Geography"])
df2_new.drop_duplicates()
df2.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn

In [49]:
df2_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Gender        968 non-null    object
 8   Target        1020 non-null   object
dtypes: float64(2), int64(5), object(2)
memory usage: 71.8+ KB

In [50]:
df2_new.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [60]:
# Challenge 8 – ML Dataset Preparation
#Prepare a machine learning dataset.
#Perform
#• Remove duplicates
#• Remove CustomerID
#• Remove Segment
#• Fill missing values
#• Rename Target to Output
#Finally
#Display
#head()
#info()
#describe()
#value_counts(Output)

df2.drop_duplicates()
df2.drop(columns=["CustomerID","Segment"])
df2["Age"] = df2["Age"].fillna(df2["Age"].median())
df2["Balance"]=df2["Balance"].fillna(df2["Balance"].median())
df2["AnnialIncome"] = df2["AnnualIncome"].fillna(df2["AnnualIncome"].mean())
df2_n=df2.rename(columns={"Target":"Output"})
df2_n.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output,AnnialIncome
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,49184.0
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,162964.0
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,26956.0
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,92926.0
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,108236.0

In [54]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
 11  AnnialIncome  1020 non-null   float64
dtypes: float64(3), int64(5), object(4)
memory usage: 95.8+ KB

In [55]:
df2.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,AnnialIncome
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765,112498.242157
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330,50925.015723
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,20227.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000,69223.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000,112358.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000,155570.750000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,199967.000000

In [62]:
df2_n["Output"].value_counts()

Output
Churn    515
Stay     505
Name: count, dtype: int64

In [64]:
# Challenge 9 – Column Transformation
#Create these new columns
#NetWorth = Balance + AnnualIncome
#AgeAfterRetirement = Age + 20
#DoubleCreditScore = CreditScore * 2
#IncomePerMonth = AnnualIncome / 12
#Then
#Display first 15 rows.

df2["NetWorth"]=df2["Balance"]+df2["AnnualIncome"]
df2["AgeAfterRetirement"]=df2["Age"]+20
df2["DoubleCreditScore"]=df2["CreditScore"]*2
df2["IncomePerMonth"]=df2["AnnualIncome"]/12
df2.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,AnnialIncome,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,49184.0,146707.535666,78,1162,4098.666667
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,162964.0,169320.540000,85,1464,13580.333333
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,26956.0,170159.920000,76,1006,2246.333333
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,92926.0,232553.880000,75,926,7743.833333
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,108236.0,184221.460000,86,788,9019.666667
5,10006,69,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay,31390.0,138635.620000,89,1540,2615.833333
6,10007,58,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn,182141.0,220598.720000,78,1782,15178.416667
7,10008,67,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay,95861.0,269157.730000,87,1076,7988.416667
8,10009,41,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay,62638.0,104539.410000,61,1326,5219.833333
9,10010,22,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn,179680.0,286507.980000,42,950,14973.333333
10,10011,44,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay,187772.0,231695.030000,64,1740,15647.666667
11,10012,69,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn,102694.0,115931.720000,89,1148,8557.833333
12,10013,59,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay,150870.0,179444.320000,79,1538,12572.500000
13,10014,52,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay,88876.0,174562.770000,72,1796,7406.333333
14,10015,26,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn,153569.0,304725.430000,46,786,12797.416667

In [66]:
# Challenge 10 – Company Report
#Display
#• first five rows
#• last five rows
#• ten random rows
#• dataset information
#• descriptive statistics
#Finally rename
#Target → Customer_Status

df2.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,AnnialIncome,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,49184.0,146707.535666,78,1162,4098.666667
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,162964.0,169320.540000,85,1464,13580.333333
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,26956.0,170159.920000,76,1006,2246.333333
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,92926.0,232553.880000,75,926,7743.833333
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,108236.0,184221.460000,86,788,9019.666667

In [67]:
df2.tail()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,AnnialIncome,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
1015,10450,43,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay,173620.0,233973.030000,63,1288,14468.333333
1016,10753,25,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn,54490.0,179002.070000,45,606,4540.833333
1017,10810,49,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay,82062.0,135912.090000,69,1626,6838.500000
1018,10267,38,112358.0,10424,722,138100.050000,6,Germany,Other,Corporate,Stay,112358.0,250458.050000,58,1444,9363.166667
1019,10059,62,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn,97504.0,195027.535666,82,860,8125.333333

In [69]:
df2.sample(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,AnnialIncome,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
746,10747,25,67125.0,38867,859,27061.33,6,UK,Female,NaN,Stay,67125.0,94186.33,45,1718,5593.750000
566,10567,51,118293.0,34205,820,89111.38,0,UK,Other,Retail,Churn,118293.0,207404.38,71,1640,9857.750000
252,10253,28,105835.0,38359,620,37966.82,2,Canada,Other,Corporate,Stay,105835.0,143801.82,48,1240,8819.583333
248,10249,43,97970.0,30223,374,137722.71,2,NaN,Female,Corporate,Churn,97970.0,235692.71,63,748,8164.166667
701,10702,56,24273.0,34422,438,198682.40,4,India,Female,Retail,Churn,24273.0,222955.40,76,876,2022.750000
863,10864,69,138789.0,3338,406,148083.38,8,USA,Male,Retail,Churn,138789.0,286872.38,89,812,11565.750000
590,10591,47,112358.0,33950,392,79357.03,8,India,NaN,Retail,Churn,112358.0,191715.03,67,784,9363.166667
142,10143,68,112358.0,24476,843,100358.95,4,USA,Female,Corporate,Stay,112358.0,212716.95,88,1686,9363.166667
964,10965,29,24876.0,41646,828,172541.96,9,Canada,Male,SME,Stay,24876.0,197417.96,49,1656,2073.000000
36,10037,54,84543.0,38440,340,123876.30,6,France,Other,SME,Churn,84543.0,208419.30,74,680,7045.250000

In [71]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          1020 non-null   int64
 1   Age                 1020 non-null   int64
 2   AnnualIncome        1020 non-null   float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             1020 non-null   float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Target              1020 non-null   object
 11  AnnialIncome        1020 non-null   float64
 12  NetWorth            1020 non-null   float64
 13  AgeAfterRetirement  1020 non-null   int64
 14  DoubleCreditScore   1020 non-null   int64
 15  IncomePerMonth      1020 non-null   float64
dtypes: float64(5), int64(7), object(4)
memory usage: 127.6+ KB

In [72]:
df2.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,AnnialIncome,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765,112498.242157,210021.777822,64.237255,1205.319608,9374.853513
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330,50925.015723,72924.053575,15.136428,353.121379,4243.751310
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,20227.000000,33432.390000,38.000000,600.000000,1685.583333
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000,69223.000000,156965.307500,51.000000,881.500000,5768.583333
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000,112358.000000,209989.700000,64.000000,1214.000000,9363.166667
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000,155570.750000,262725.185000,77.000000,1514.500000,12964.229167
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,199967.000000,390628.400000,90.000000,1800.000000,16663.916667

In [73]:
df2.rename(columns={"Target":"Customer_Status"})

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status,AnnialIncome,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,49184.0,146707.535666,78,1162,4098.666667
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,162964.0,169320.540000,85,1464,13580.333333
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,26956.0,170159.920000,76,1006,2246.333333
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,92926.0,232553.880000,75,926,7743.833333
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,108236.0,184221.460000,86,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay,173620.0,233973.030000,63,1288,14468.333333
1016,10753,25,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn,54490.0,179002.070000,45,606,4540.833333
1017,10810,49,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay,82062.0,135912.090000,69,1626,6838.500000
1018,10267,38,112358.0,10424,722,138100.050000,6,Germany,Other,Corporate,Stay,112358.0,250458.050000,58,1444,9363.166667
1019,10059,62,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn,97504.0,195027.535666,82,860,8125.333333

In [74]:
# Challenge 11 – Missing Value Report
#Create a report showing
#• Total missing values
#• Numerical columns
#• Mean of Balance
#• Median of Age
#• Fill missing values
#• Display information again

df2.isnull().sum()

CustomerID             0
Age                    0
AnnualIncome           0
Spending               0
CreditScore            0
Balance                0
Tenure                 0
Geography             51
Gender                52
Segment               51
Target                 0
AnnialIncome           0
NetWorth               0
AgeAfterRetirement     0
DoubleCreditScore      0
IncomePerMonth         0
dtype: int64

In [75]:
df2.select_dtypes(include="number").columns

Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'AnnialIncome', 'NetWorth', 'AgeAfterRetirement',
       'DoubleCreditScore', 'IncomePerMonth'],
      dtype='object')

In [76]:
df2["Balance"].mean()

np.float64(97523.53566563467)

In [77]:
df2["Age"].median()

44.0

In [82]:
df2["AnnualIncome"].fillna(df2["AnnualIncome"].median())
df2["Balance"].fillna(df2["Balance"].mean())
df2["Age"].fillna(df2["Age"].median())

0       58
1       65
2       56
3       55
4       66
        ..
1015    43
1016    25
1017    49
1018    38
1019    62
Name: Age, Length: 1020, dtype: int64

In [83]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          1020 non-null   int64
 1   Age                 1020 non-null   int64
 2   AnnualIncome        1020 non-null   float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             1020 non-null   float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Target              1020 non-null   object
 11  AnnialIncome        1020 non-null   float64
 12  NetWorth            1020 non-null   float64
 13  AgeAfterRetirement  1020 non-null   int64
 14  DoubleCreditScore   1020 non-null   int64
 15  IncomePerMonth      1020 non-null   float64
dtypes: float64(5), int64(7), object(4)
memory usage: 127.6+ KB

In [85]:
# Challenge 12 – Customer Classification
#Count
#Stay
#Churn
#Then
#Rename
#Target → Customer_Class
#Convert it into string.

df2["Target"].value_counts()

Target
Churn    515
Stay     505
Name: count, dtype: int64

In [96]:
df2=df2.rename(columns={"Target":"Customer_Class"})
df2

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Class,AnnialIncome,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,49184.0,146707.535666,78,1162,4098.666667
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,162964.0,169320.540000,85,1464,13580.333333
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,26956.0,170159.920000,76,1006,2246.333333
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,92926.0,232553.880000,75,926,7743.833333
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,108236.0,184221.460000,86,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay,173620.0,233973.030000,63,1288,14468.333333
1016,10753,25,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn,54490.0,179002.070000,45,606,4540.833333
1017,10810,49,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay,82062.0,135912.090000,69,1626,6838.500000
1018,10267,38,112358.0,10424,722,138100.050000,6,Germany,Other,Corporate,Stay,112358.0,250458.050000,58,1444,9363.166667
1019,10059,62,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn,97504.0,195027.535666,82,860,8125.333333

In [97]:
df2["Customer_Class"]=df2["Customer_Class"].astype(str)
df2

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Class,AnnialIncome,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,49184.0,146707.535666,78,1162,4098.666667
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,162964.0,169320.540000,85,1464,13580.333333
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,26956.0,170159.920000,76,1006,2246.333333
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,92926.0,232553.880000,75,926,7743.833333
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,108236.0,184221.460000,86,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay,173620.0,233973.030000,63,1288,14468.333333
1016,10753,25,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn,54490.0,179002.070000,45,606,4540.833333
1017,10810,49,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay,82062.0,135912.090000,69,1626,6838.500000
1018,10267,38,112358.0,10424,722,138100.050000,6,Germany,Other,Corporate,Stay,112358.0,250458.050000,58,1444,9363.166667
1019,10059,62,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn,97504.0,195027.535666,82,860,8125.333333

In [100]:
# Challenge 13 – Sales Department
#Rename
#Balance → AccountBalance
#AnnualIncome → Salary
#CreditScore → Score
#Add prefix
#Sales_
#Then
#Display
#sample(20)

df2=df2.rename(columns={"Balance":"AccountBalance","AnnualIncome":"Salary",
                    "CreditScore":"Score"})
df2=df2.add_prefix("Sales_")
df2.sample(20)

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Customer_Class,Sales_AnnialIncome,Sales_NetWorth,Sales_AgeAfterRetirement,Sales_DoubleCreditScore,Sales_IncomePerMonth
908,10909,44,57654.0,14117,610,94922.630000,8,UK,Male,SME,Stay,57654.0,152576.630000,64,1220,4804.500000
409,10410,18,55969.0,46473,311,97523.535666,5,Germany,Other,SME,Churn,55969.0,153492.535666,38,622,4664.083333
817,10818,68,92836.0,17018,435,123159.550000,4,UK,Male,SME,Churn,92836.0,215995.550000,88,870,7736.333333
123,10124,46,112358.0,32241,653,97523.535666,8,Canada,Female,Corporate,Stay,112358.0,209881.535666,66,1306,9363.166667
439,10440,58,162516.0,1779,691,156383.150000,5,Canada,Other,Corporate,Stay,162516.0,318899.150000,78,1382,13543.000000
655,10656,24,45048.0,4680,784,109686.750000,0,Canada,Other,Retail,Churn,45048.0,154734.750000,44,1568,3754.000000
761,10762,54,184882.0,35165,389,97523.535666,9,France,Female,NaN,Churn,184882.0,282405.535666,74,778,15406.833333
180,10181,50,166466.0,44281,662,14415.100000,0,Canada,Male,Corporate,Churn,166466.0,180881.100000,70,1324,13872.166667
12,10013,59,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay,150870.0,179444.320000,79,1538,12572.500000
231,10232,61,137944.0,24811,680,88787.860000,1,Germany,Male,SME,Churn,137944.0,226731.860000,81,1360,11495.333333
268,10269,51,118782.0,21062,477,91932.710000,8,UK,Other,Corporate,Churn,118782.0,210714.710000,71,954,9898.500000
248,10249,43,97970.0,30223,374,137722.710000,2,NaN,Female,Corporate,Churn,97970.0,235692.710000,63,748,8164.166667
725,10726,63,25633.0,3105,553,184454.020000,4,UK,Female,Corporate,Stay,25633.0,210087.020000,83,1106,2136.083333
688,10689,44,188009.0,21604,413,19251.260000,10,India,Male,Retail,Churn,188009.0,207260.260000,64,826,15667.416667
941,10942,64,150838.0,18752,895,118729.990000,10,Canada,Female,Corporate,Stay,150838.0,269567.990000,84,1790,12569.833333
443,10444,66,77517.0,38228,697,70960.930000,2,USA,Male,SME,Stay,77517.0,148477.930000,86,1394,6459.750000
228,10229,45,91973.0,42408,358,15008.230000,10,Canada,Female,SME,Churn,91973.0,106981.230000,65,716,7664.416667
593,10594,66,147832.0,15687,364,52871.420000,3,India,Other,Retail,Churn,147832.0,200703.420000,86,728,12319.333333
760,10761,44,106300.0,35040,723,104929.240000,3,Germany,Male,Retail,Stay,106300.0,211229.240000,64,1446,8858.333333
617,10618,46,62413.0,7071,519,101668.710000,5,Germany,Other,SME,Stay,62413.0,164081.710000,66,1038,5201.083333

In [109]:
# Challenge 14 – Interview Challenge
#Without creating another DataFrame,
#perform
#• remove duplicates
#• rename Target
#• fill missing values
#• convert Balance to float
#• display summary

df2 = pd.read_csv("C:\\Users\\DELL\\Downloads\\Task_dataset - Task_dataset.csv")
df2.drop_duplicates(inplace=True)
df2.rename(columns={"Target":"Customer_Status"},inplace=True)
df2["Age"].fillna(df2["Age"].median(), inplace=True)
df2["AnnualIncome"].fillna(df2["AnnualIncome"].median(), inplace=True)
df2["Balance"].fillna(df2["Balance"].mean(), inplace=True)
df2["Balance"]=df2["Balance"].astype(float)
df2.describe()

C:\Users\DELL\AppData\Local\Temp\ipykernel_15408\2952940832.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["Age"].fillna(df2["Age"].median(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_15408\2952940832.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["AnnualIncome"].fillna(df2["AnnualIncome"].median(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_15408\2952940832.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["Balance"].fillna(df2["Balance"].mean(), inplace=True)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112452.763000,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.130834,51081.480963,14211.735656,176.605486,54430.062006,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [6]:
# Challenge 15 – Data Engineer Task
#Load the dataset.
#Create another DataFrame containing only numeric columns.
#Drop
#CustomerID
#Target
#Display summary.

import pandas as pd
df2 = pd.read_csv("C:\\Users\\DELL\\Downloads\\Task_dataset - Task_dataset.csv")
df3 = df2.select_dtypes(include="number")
df3.drop(columns=["CustomerID"],inplace=True)
df3.describe()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [9]:
# Challenge 16 – Mixed Cleaning
#Perform
#drop_duplicates()
#fillna()
#astype()
#rename()
#head()
#info()
#using only one DataFrame variable.

df2.drop_duplicates(inplace=True)
df2["Age"]=df2["Age"].fillna(df2["Age"].median())
df2["AnnualIncome"]=df2["AnnualIncome"].fillna(df2["AnnualIncome"].median())
df2["Balance"]=df2["Balance"].fillna(df2["Balance"].mean())
df2["Balance"]=df2["Balance"].astype(float)
df2.rename(columns={"Target":"Customer_Status"},inplace=True)
df2.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1000 non-null   int64
 1   Age              1000 non-null   float64
 2   AnnualIncome     1000 non-null   float64
 3   Spending         1000 non-null   int64
 4   CreditScore      1000 non-null   int64
 5   Balance          1000 non-null   float64
 6   Tenure           1000 non-null   int64
 7   Geography        950 non-null    object
 8   Gender           950 non-null    object
 9   Segment          950 non-null    object
 10  Customer_Status  1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [11]:
# Challenge 17 – Real Company Dataset
#Manager asks
#Remove duplicate records
#Fill missing values
#Rename all business columns
#Add company prefix
#Display summary
#Display target counts

df2.drop_duplicates(inplace=True)
df2["Age"] = df2["Age"].fillna(df2["Age"].median())
df2["AnnualIncome"] = df2["AnnualIncome"].fillna(df2["AnnualIncome"].median())
df2["Balance"] = df2["Balance"].fillna(df2["Balance"].mean())
df2.rename(columns={"CustomerID": "Employee_ID","Age": "Employee_Age","Gender": "Employee_Gender",
    "AnnualIncome": "Salary","Target": "Customer_Status"}, inplace=True)
df2 = df2.add_prefix("Company_")
df2.describe()

,Company_Employee_ID,Company_Employee_Age,Company_Salary,Company_Spending,Company_CreditScore,Company_Balance,Company_Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112452.763000,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.130834,51081.480963,14211.735656,176.605486,54430.062006,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [12]:
df2["Company_Customer_Status"].value_counts()

Company_Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

In [20]:
# Challenge 18 – Customer Summary
#Generate
#Mean Balance
#Median Balance
#Mean Age
#Median AnnualIncome
#Then
#fill missing values using these statistics.

import pandas as pd
df2 = pd.read_csv(r"C:\Users\DELL\Downloads\Task_dataset - Task_dataset.csv")
print("Mean Balance:", df2["Balance"].mean())
print("Median Balance:",df2["Balance"].median())
print("Median AnnualIncome:",df2["AnnualIncome"].median())
df2["Balance"] = df2["Balance"].fillna(df2["Balance"].mean())
df2["Age"] = df2["Age"].fillna(df2["Age"].mean())
df2["AnnualIncome"] = df2["AnnualIncome"].fillna(df2["AnnualIncome"].median())
df2.info()

Mean Balance: 97523.53566563467
Median Balance: 95100.06
Median AnnualIncome: 112358.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [21]:
# Challenge 19 – Transformation Challenge
#Create
#Income_in_Lakhs
#Balance_in_Lakhs
#SeniorCitizen
#HighCreditScore
#where
#SeniorCitizen = Age + 0
#HighCreditScore = CreditScore * 1
#(No conditional statements.)

df2["Income_in_Lakhs"] = df2["AnnualIncome"]/100000
df2["Balance_in_Lakhs"]=df2["Balance"]/100000
df2["SeniorCitizen"]=df2["Age"]+0
df2["HighCreditScore"]=df2["CreditScore"]*1
df2.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,0.49184,0.975235,58.0,581
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,1.62964,0.063565,65.0,732
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,0.26956,1.432039,56.0,503
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,0.92926,1.396279,55.0,463
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,1.08236,0.759855,66.0,394

In [23]:
# Challenge 20 – Final Interview Project
#Your manager gives you a dirty customer dataset.
#Prepare the final dataset.
#Requirements
#Load dataset
#Check information
#Find missing values
#Remove duplicates
#Rename
#CustomerID
#AnnualIncome
#CreditScore
#Target
#Convert
#Age
#AnnualIncome
#Balance
#Fill missing values
#Remove
#Segment
#CustomerID
#Create new columns
#TotalMoney = Balance + AnnualIncome
#AgeAfter5Years = Age + 5
#MonthlyIncome = AnnualIncome / 12
#CreditScoreDouble = CreditScore * 2Display
#• Head
#• Tail
#• Sample
#• Describe
#• Target counts
#• Final information

import pandas as pd
df2 = pd.read_csv("C:\\Users\\DELL\\Downloads\\Task_dataset - Task_dataset.csv")
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [24]:
df2.isnull().sum()

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [26]:
df2.drop_duplicates(inplace=True)
df2

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [30]:
df2.rename(columns={"CustomerID": "Customer_ID","AnnualIncome": "Income",
    "CreditScore": "Credit_Score","Target": "Customer_Status"}, inplace=True)
df2["Age"] = df2["Age"].fillna(df2["Age"].median())
df2["Income"] = df2["Income"].fillna(df2["Income"].median())
df2["Balance"] = df2["Balance"].fillna(df2["Balance"].mean())
df2["Age"] = df2["Age"].astype(int)
df2["Income"] = df2["Income"].astype(float)
df2["Balance"] = df2["Balance"].astype(float)
df2.drop(columns=["Segment", "Customer_ID"], inplace=True)
df2["TotalMoney"] = df2["Balance"] + df2["Income"]
df2["AgeAfter5Years"] = df2["Age"] + 5
df2["MonthlyIncome"] = df2["Income"] / 12
df2["CreditScoreDouble"] = df2["Credit_Score"] * 2
df2.head()

,Age,Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Customer_Status,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,58,49184.0,2139,581,97557.565779,2,France,Male,Stay,146741.565779,63,4098.666667,1162
1,65,162964.0,6197,732,6356.540000,1,USA,Male,Churn,169320.540000,70,13580.333333,1464
2,56,26956.0,37281,503,143203.920000,8,Canada,Male,Stay,170159.920000,61,2246.333333,1006
3,55,92926.0,925,463,139627.880000,5,NaN,Male,Churn,232553.880000,60,7743.833333,926
4,66,108236.0,7198,394,75985.460000,5,UK,Other,Churn,184221.460000,71,9019.666667,788

In [31]:
df2.tail()

,Age,Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Customer_Status,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
995,34,81731.0,40980,761,181465.65,5,Germany,Other,Stay,263196.65,39,6810.916667,1522
996,47,42475.0,1176,780,26640.99,5,France,Female,Stay,69115.99,52,3539.583333,1560
997,31,120531.0,46929,733,147220.82,4,India,Male,Stay,267751.82,36,10044.250000,1466
998,21,33661.0,22314,540,94186.48,5,NaN,Other,Stay,127847.48,26,2805.083333,1080
999,63,31930.0,851,559,100908.40,6,UK,Female,Stay,132838.40,68,2660.833333,1118

In [33]:
df2.sample(10)

,Age,Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Customer_Status,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
715,38,110315.0,39420,324,153936.26,2,UK,Other,Churn,264251.26,43,9192.916667,648
769,69,29321.0,42813,439,96299.10,10,Canada,Other,Churn,125620.10,74,2443.416667,878
954,40,34797.0,43835,550,49522.79,10,UK,Other,Stay,84319.79,45,2899.750000,1100
905,41,124217.0,10195,737,73925.99,5,India,Female,Stay,198142.99,46,10351.416667,1474
737,48,190280.0,25007,488,170425.89,7,Canada,Male,Churn,360705.89,53,15856.666667,976
893,68,88159.0,15362,795,74380.46,4,India,Male,Stay,162539.46,73,7346.583333,1590
551,27,33910.0,44425,357,39980.48,2,UK,Other,Churn,73890.48,32,2825.833333,714
163,64,112347.5,28685,762,177618.20,6,UK,NaN,Stay,289965.70,69,9362.291667,1524
341,68,105047.0,25746,312,58369.47,6,India,Other,Churn,163416.47,73,8753.916667,624
183,23,134481.0,7437,549,87135.31,6,Germany,Male,Stay,221616.31,28,11206.750000,1098

In [34]:
df2.describe()

,Age,Income,Spending,Credit_Score,Balance,Tenure,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,44.202000,112452.763000,25285.558000,603.088000,97557.565779,5.241000,210010.328779,49.202000,9371.063583,1206.176000
std,15.130834,51081.480963,14211.735656,176.605486,54430.062006,3.179155,73150.769298,15.130834,4256.790080,353.210972
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,33432.390000,23.000000,1685.583333,600.000000
25%,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000,156611.867500,36.000000,5703.104167,882.000000
50%,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000,209916.897889,49.000000,9362.291667,1213.000000
75%,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000,263542.793945,62.000000,12964.229167,1516.500000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,390628.400000,75.000000,16663.916667,1800.000000

In [35]:
df2["Customer_Status"].value_counts()

Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   Income             1000 non-null   float64
 2   Spending           1000 non-null   int64
 3   Credit_Score       1000 non-null   int64
 4   Balance            1000 non-null   float64
 5   Tenure             1000 non-null   int64
 6   Geography          950 non-null    object
 7   Gender             950 non-null    object
 8   Customer_Status    1000 non-null   object
 9   TotalMoney         1000 non-null   float64
 10  AgeAfter5Years     1000 non-null   int64
 11  MonthlyIncome      1000 non-null   float64
 12  CreditScoreDouble  1000 non-null   int64
dtypes: float64(4), int64(6), object(3)
memory usage: 109.4+ KB