### Exam Task on Pandas Method (Data Cleaning)

#### Part 1 — Inspect & Understand the Dataset

In [2]:
# Q1. Load the dataset
#Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
#Then display the first 10 rows.
#Use: pd.read_csv(), head()

import pandas as pd
df = pd.read_csv("C:\\Users\\DELL\\Downloads\\customer_analytics - customer_analytics.csv")
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [3]:
# Q2. Inspect the end of the dataset
#Display the last 15 rows.
#Use: tail()

df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [4]:
#Q3. Random inspection
#Display 10 random records.
#Use: sample()

df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1247,101794,29,192670,36602.22,333,11,NaN,Retail,Agent,2024-02-24 00:00:00,No,High,9889.97,101,2.5
1504,100791,48,185443,112066.44,479,11,Delhi,Retail,Agent,NaN,Yes,High,32235.41,55,9.3
943,101906,74,99813,238952.56,499,7,Mumbai,SME,Agent,2021-08-14 00:00:00,Yes,High,44088.83,142,3.1
292,100317,59,182087,140090.4,675,10,Chennai,SME,Branch,2021-09-28 00:00:00,Yes,Medium,3446.55,135,6.6
96,101884,51,153202,96008.19,554,6,NaN,SME,Branch,2024-02-10 00:00:00,Yes,Medium,35388.8,74,1.8
1543,100314,40,142832,178045.73,808,7,mumbai,SME,Agent,2023-09-22 00:00:00,Yes,Low,19593.75,139,2.6
1812,101255,61,48387,212002.66,610,7,Bangalore,Corporate,Online,2025-02-24 00:00:00,No,Medium,46534.25,42,2.2
886,100635,29,50537,228744.87,845,13,Kolkata,Corporate,Agent,2021-02-18 00:00:00,Yes,Low,4655.61,138,6.0
815,100989,31,64922,121370.6,555,9,Kolkata,Premium,Branch,2021-08-23 00:00:00,Yes,Medium,48132.76,60,9.2
648,100825,61,150703,106791.31,313,6,Mumbai,Premium,Online,2024-06-08 00:00:00,Yes,High,31457.18,84,2.3

In [5]:
# Q4. Dataset audit
#Use info() to identify:
#• Number of rows
#• Number of columns
#• Columns with missing values
#• Columns having incorrect/object datatypes
#Use: info()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [6]:
# Q5. Missing-value audit
#Calculate the number of missing values in every column.
#Then verify the result using both:
#isnull()
#and
#isna()

df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [7]:
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

### Part 2 — Detect & Fix Data Quality Problems

In [8]:
# Q6. Duplicate investigation
#Find how many duplicate rows exist.
#Do not remove them yet.
#Use: duplicated()

df.duplicated().sum()

np.int64(40)

In [11]:
# Q7. Remove duplicates
#Remove all duplicate records and store the cleaned result back into df.
#Then verify that duplicates no longer exist.
#Use: drop_duplicates(), duplicated()

df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [13]:
# Q8. Numeric column investigation
#Select only numeric columns.
#Identify which columns are currently numeric and which potentially numeric columns have
#become object because of invalid values.
#Use: select_dtypes()

numeric_columns = df.select_dtypes(include="number")
numeric_columns.columns

Index(['Customer_ID', 'Tenure_Years', 'Satisfaction_Score'], dtype='object')

In [15]:
object_columns = df.select_dtypes(include="object")
object_columns.columns

Index(['Age', 'Annual_Income', 'Account_Balance', 'Credit_Score', 'City',
       'Segment', 'Channel', 'Join_Date', 'Active', 'Risk_Level',
       'Monthly_Spend', 'Transactions'],
      dtype='object')

In [18]:
# Q9. Fix Age
#The Age column contains:
#• Valid numbers
#• Missing values
#• Invalid text such as unknown, N/A, etc.
#Convert Age into a proper numeric column.
#Invalid values should become missing values.
#Then fill missing Age values using the median age.
#Use: pd.to_numeric(), median(), fillna()

df["Age"] = pd.to_numeric(df["Age"],errors="coerce")
df["Age"].isna().sum()

np.int64(127)

In [20]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Age"].isna().sum()

np.int64(0)

In [22]:
# Q10. Fix Annual Income
#Clean Annual_Income.
#Requirements:
#1. Convert invalid values to missing.
#2. Convert the column to a numeric datatype.
#3. Calculate the median.
#4. Fill missing values using the median.
#Use: pd.to_numeric(), median(), fillna(), astype()

df["Annual_Income"] = pd.to_numeric(df["Annual_Income"],errors="coerce")
df["Annual_Income"].isna().sum()

np.int64(149)

In [25]:
median_income = df["Annual_Income"].median()
df["Annual_Income"].dtype

dtype('float64')

In [26]:
df["Annual_Income"] = df["Annual_Income"].fillna(median_income)

In [30]:
df["Annual_Income"] = df["Annual_Income"].astype(float)
df[["Annual_Income"]].head(10)

   Annual_Income
0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
5        37087.0
6        67229.0
7       139914.0
8       153267.0
9       139914.0

### Part 3 — Numerical Cleaning

In [32]:
# Q11. Clean Account Balance
#The Account_Balance column contains invalid strings and missing values.
#Clean the column and replace missing values with the mean Account Balance.
#Use:
#• pd.to_numeric()
#• mean()
#• fillna()

df["Account_Balance"] = pd.to_numeric(df["Account_Balance"],errors="coerce")
df["Account_Balance"] = df["Account_Balance"].fillna(df["Account_Balance"].mean())
df["Account_Balance"].isna().sum()

np.int64(0)

In [35]:
# Q12. Clean Credit Score
#Clean Credit_Score.
#Invalid values should become missing.
#Then replace missing values with the median Credit Score.
#Finally convert the column to integer.
#Use:
#• pd.to_numeric()
#• median()
#• fillna()
#• astype()

df["Credit_Score"] = pd.to_numeric(df["Credit_Score"],errors = "coerce")
df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].median())
df["Credit_Score"] = df["Credit_Score"].astype(int)
df["Credit_Score"].isna().sum(),df["Credit_Score"].dtype

(np.int64(0), dtype('int64'))

In [36]:
# Q13. Clean Monthly Spend
#Clean Monthly_Spend.
#Then:
#• Convert it to numeric.
#• Replace invalid values.
#• Replace missing values using the median.
#• Make sure the final column is numeric.

df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"],errors="coerce")
df["Monthly_Spend"] = df["Monthly_Spend"].fillna(df["Monthly_Spend"].median())
df["Monthly_Spend"].isna().sum(),df["Monthly_Spend"].dtype

(np.int64(0), dtype('float64'))

In [37]:
# Q14. Clean Transactions
#The Transactions column contains invalid strings.
#Convert it to numeric and replace invalid values with the median number of transactions.
#Then convert the final column to integer.

df["Transactions"] = pd.to_numeric(df["Transactions"],errors="coerce")
df["Transactions"] = df["Transactions"].fillna(df["Transactions"].median())
df["Transactions"] = df["Transactions"].astype(int)
df["Transactions"].isna().sum(),df["Transactions"].dtype

(np.int64(0), dtype('int64'))

In [39]:
# Q15. Clean Satisfaction Score
#Clean Satisfaction_Score.
#Replace missing/invalid values using the mean Satisfaction Score.
#Then convert the column to float.

df["Satisfaction_Score"] = pd.to_numeric(df["Satisfaction_Score"],errors="coerce")
df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(df["Satisfaction_Score"].mean())
df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)
df["Satisfaction_Score"].isna().sum(),df["Satisfaction_Score"].dtype

(np.int64(0), dtype('float64'))

### Part 4 — Date Cleaning

In [41]:
# Q16. Investigate Join_Date
#Inspect the Join_Date column.
#Identify the problems caused by:
#• Missing dates
#• Different date formats
#• Invalid date strings
#Do not clean it yet.

df["Join_Date"].head(20),df["Join_Date"].isna().sum(),df["Join_Date"].dtype
df["Join_Date"].value_counts().head(10)

Join_Date
not_a_date             11
unknown                 8
31/99/2024              6
2025-10-31 00:00:00     5
2022-06-26 00:00:00     5
2022-07-24 00:00:00     5
2023-07-19 00:00:00     5
2023-12-24 00:00:00     5
2024-01-10 00:00:00     5
2022-06-28 00:00:00     5
Name: count, dtype: int64

In [49]:
# Q17. Convert Join_Date
#Convert Join_Date into a proper Pandas datetime column.
#Any invalid dates should become missing values.
#Use: pd.to_datetime()

df = pd.read_csv("C:\\Users\\DELL\\Downloads\\customer_analytics - customer_analytics.csv")
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df["Join_Date"].isna().sum(),df["Join_Date"].dtype

(np.int64(128), dtype('<M8[ns]'))

In [50]:
# Q18. Handle missing dates
#After conversion, find how many missing dates remain.
#Then replace missing dates appropriately using a reasonable date-based strategy.

df["Join_Date"] = df["Join_Date"].fillna(df["Join_Date"].median())
df["Join_Date"].isna().sum()

np.int64(0)

### Part 5 — Categorical Cleaning

In [51]:
# Q19. Clean City
#The City column contains values such as:
#Mumbai
#mumbai
#Mumbai
#mumbai
#Standardize the values so that logically identical cities are represented consistently.
#Then check the unique frequency distribution.
#Use: replace(), value_counts()

df["City"] = df["City"].replace({"mumbai":"Mumbai","hyderabad":"Hyderabad","bangalore":"Bangalore","pune":"Pune","delhi":"Delhi","kolkata":"Kolkata","chennai":"Chennai"})
df["City"].value_counts(dropna=False)

City
Mumbai       314
Hyderabad    298
Delhi        288
Kolkata      276
Pune         274
Chennai      255
Bangalore    254
NaN           81
Name: count, dtype: int64

In [53]:
# Q20. Analyze Segment
#Check the frequency of:
#Retail
#SME
#Corporate
#Premium
#Also determine whether missing values exist.
#Then replace missing Segment values with the most appropriate category based on your
#analysis.
#Use: value_counts(), fillna()

df["Segment"] = df["Segment"].fillna("Retail")
df["Segment"].isna().sum(),df["Segment"].value_counts()

(np.int64(0),
 Segment
 Retail       586
 Premium      523
 Corporate    475
 SME          456
 Name: count, dtype: int64)

In [55]:
#Q21. Clean Active
#Active is supposed to be a binary column, but it contains:
#Yes
#No
#Y
#N
#YES
#NO
#yes
#no
#1
#0
#Transform these into a consistent representation:
#Yes
#No
#Then verify the result with value_counts().
#Use: replace(), value_counts()

df["Active"] = df["Active"].replace({"Yes":"Yes","YES":"Yes","yes":"Yes","Y":"Yes",1:"Yes","1":"Yes","No":"No","NO":"No","no":"No",
                                     "N":"No",0:"No","0":"No"})
df["Active"].value_counts(dropna=False)

Active
Yes    1371
No      610
NaN      59
Name: count, dtype: int64

In [59]:
#Q22. Clean Risk_Level
#Check the distribution of:
#High
#Medium
#Low
#Verify whether missing values exist.
#Then display the final class distribution.

df["Risk_Level"].value_counts(dropna=False)
df["Risk_Level"].isna().sum()

np.int64(0)

In [60]:
df["Risk_Level"].value_counts()

Risk_Level
High      1009
Low        548
Medium     483
Name: count, dtype: int64

### Part 6 — Column Transformation

In [62]:
# Q23. Rename columns
#Rename these columns:
#Customer_ID → Customer_ID
#Annual_Income → AnnualIncome
#Account_Balance → AccountBalance
#Credit_Score → CreditScore
#Tenure_Years → Tenure
#Join_Date → CustomerJoinDate
#Risk_Level → RiskLevel
#Monthly_Spend → MonthlySpend
#Satisfaction_Score → SatisfactionScore
#Use rename().

df = df.rename(columns={"Customer_ID":"Customer_ID","Annual_Income":"AnnualIncome","Account_Balance":"AccountBalance",
                        "Credit_Score":"CreditScore","Tenure_Years":"Tenure","Join_Date":"CustomerJoinDate","Risk_Level":"RiskLevel",
                        "Monthly_Spend":"MonthlySpend","Satisfaction_Score":"SatisfactionScore"})
df.columns

Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore'],
      dtype='object')

In [63]:
# Q24. Add a prefix
#Add:
#Customer_
#to every column.
#Example:
#Age
#becomes:
#Customer_Age
#Use: add_prefix()

df = df.add_prefix("Customer_")
df.columns

Index(['Customer_Customer_ID', 'Customer_Age', 'Customer_AnnualIncome',
       'Customer_AccountBalance', 'Customer_CreditScore', 'Customer_Tenure',
       'Customer_City', 'Customer_Segment', 'Customer_Channel',
       'Customer_CustomerJoinDate', 'Customer_Active', 'Customer_RiskLevel',
       'Customer_MonthlySpend', 'Customer_Transactions',
       'Customer_SatisfactionScore'],
      dtype='object')

In [69]:
# Q25. Remove unnecessary column
#Determine whether Customer_ID should be retained for analysis.
#Create a cleaned DataFrame without the identifier column.
#Use: drop()

df = df.drop(columns=["Customer_Customer_ID"],errors="ignore")
"Customer_Customer_ID" in df.columns

False

### Part 7 — Create New Columns

In [74]:
# Q26. Create Annual Income in Lakhs
#Create:
#Income_Lakhs
#using:
#AnnualIncome / 100000
#Then check the first 10 records.

df["Customer_AnnualIncome"] = pd.to_numeric(df["Customer_AnnualIncome"],errors="coerce")
df["Income_Lakhs"] = df["Customer_AnnualIncome"] / 100000
df[["Customer_AnnualIncome","Income_Lakhs"]].head(10)

   Customer_AnnualIncome  Income_Lakhs
0                44033.0       0.44033
1               215546.0       2.15546
2               226403.0       2.26403
3                87824.0       0.87824
4                31570.0       0.31570
5                37087.0       0.37087
6                67229.0       0.67229
7                    NaN           NaN
8               153267.0       1.53267
9                    NaN           NaN

In [80]:
# Q27. Create Monthly Income
#Create:
#MonthlyIncome
#using:
#AnnualIncome / 12
#Then create:
#Income_After_Spending
#using:
#MonthlyIncome - MonthlySpend

df["Customer_MonthlySpend"] = pd.to_numeric(df["Customer_MonthlySpend"], errors="coerce")
df["MonthlyIncome"] = df["Customer_AnnualIncome"] / 12
df["Income_After_Spending"] = df["MonthlyIncome"] - df["Customer_MonthlySpend"]
df[["MonthlyIncome","Customer_MonthlySpend","Income_After_Spending"]].head(10)

   MonthlyIncome  Customer_MonthlySpend  Income_After_Spending
0    3669.416667               23066.19          -19396.773333
1   17962.166667                    NaN                    NaN
2   18866.916667               28536.34           -9669.423333
3    7318.666667               12869.71           -5551.043333
4    2630.833333               34163.02          -31532.186667
5    3090.583333               15121.16          -12030.576667
6    5602.416667               17655.61          -12053.193333
7            NaN                1720.85                    NaN
8   12772.250000               38043.07          -25270.820000
9            NaN               11472.36                    NaN

In [85]:
# Q28. Create Balance-to-Income Ratio
#Create:
#Balance_Income_Ratio
#using:
#AccountBalance / AnnualIncome
#Then inspect the first 10 rows.
#Think carefully about division by zero and missing values.

df["Customer_AccountBalance"] = pd.to_numeric(df["Customer_AccountBalance"], errors="coerce")
df["Customer_AnnualIncome"] = pd.to_numeric(df["Customer_AnnualIncome"], errors="coerce")
df["Balance_Income_Ratio"] = df["Customer_AccountBalance"] / df["Customer_AnnualIncome"].replace(0,float("nan"))
df[["Customer_AccountBalance", "Customer_AnnualIncome", "Balance_Income_Ratio"]].head(10)

   Customer_AccountBalance  Customer_AnnualIncome  Balance_Income_Ratio
0                111350.85                44033.0              2.528805
1                254378.37               215546.0              1.180158
2                159975.42               226403.0              0.706596
3                295741.60                87824.0              3.367435
4                242423.78                31570.0              7.678929
5                180084.44                37087.0              4.855730
6                 99629.81                67229.0              1.481947
7                 61030.94                    NaN                   NaN
8                221707.97               153267.0              1.446547
9                 41126.84                    NaN                   NaN

### Part 8 — Final Real-World Cleaning Challenge

In [87]:
#Q29. Prepare the ML-ready dataset
#Perform the following complete pipeline:
#1. Load the dataset.
#2. Inspect the first 10 rows.
#3. Inspect the last 10 rows.
#4. Inspect 10 random records.
#5. Run info().
#6. Check missing values.
#7. Check duplicates.
#8. Remove duplicates.
#9. Clean all numeric columns.
#10. Convert invalid numeric values to missing.
#11. Fill numerical missing values appropriately.
#12. Convert Join_Date to datetime.
#13. Handle invalid dates.
#14. Standardize categorical values.
#15. Clean the binary Active column.
#16. Rename the columns.
#17. Remove unnecessary columns.
#18. Verify the final datatypes.
#19. Generate descriptive statistics.
#20. Check categorical distributions.

df = pd.read_csv("C:\\Users\\DELL\\Downloads\\customer_analytics - customer_analytics.csv")
print(df.head(10))

   Customer_ID Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0       101317  55         44033       111350.85          772             3
1       101001  32        215546       254378.37          374             8
2       101069  23        226403       159975.42          668            12
3       101968  66         87824        295741.6          315            14
4       100530  67         31570       242423.78          370             4
5       101334  68         37087       180084.44          738             1
6       100415  47         67229        99629.81          464             4
7       100983  65           NaN        61030.94          554            15
8       100417  63        153267       221707.97          508             5
9       101472  42       missing        41126.84          556             3

        City    Segment Channel            Join_Date Active Risk_Level  \
0  Bangalore        SME   Agent  2022-08-15 00:00:00    Yes        Low
1      Delhi     Retail   Agent  2025-01-11 00:00:00    Yes       High
2    Chennai    Premium   Agent  2024-08-01 00:00:00     No     Medium
3     Mumbai    Premium   Agent  2021-05-15 00:00:00    Yes       High
4  bangalore     Retail   Agent  2026-02-03 00:00:00     No       High
5    Chennai    Premium   Agent  2023-06-04 00:00:00    Yes        Low
6    Chennai     Retail  Online  2024-01-16 00:00:00    Yes       High
7    Kolkata        SME   Agent  2024-06-26 00:00:00    Yes     Medium
8  Hyderabad    Premium  Mobile  2025-03-12 00:00:00    Yes       High
9    Kolkata  Corporate  Mobile  2021-10-07 00:00:00    Yes     Medium

  Monthly_Spend Transactions  Satisfaction_Score
0      23066.19          135                 3.1
1           NaN          106                 8.2
2      28536.34          146                 6.3
3      12869.71          115                 9.7
4      34163.02           94                 3.7
5      15121.16            6                 8.5
6      17655.61           31                 2.8
7       1720.85          139                 9.7
8      38043.07           76                 7.1
9      11472.36          124                 9.1

In [88]:
print(df.tail(10))

      Customer_ID Age Annual_Income Account_Balance Credit_Score  \
2030       100122  41        201611        40736.71          507
2031       101639  61        128850        266135.8          840
2032       101045  33         88037       129948.93          449
2033       101725  43        122756        36633.45          487
2034       101096  18        189232       235131.72          306
2035       101131  42         88530       153490.72          677
2036       101295  31        205738        270989.4          392
2037       100861  25        211994       160507.65          737
2038       101460  64         30105        32117.15          794
2039       101127  55        248332       274980.99          783

      Tenure_Years       City    Segment Channel            Join_Date Active  \
2030            15  Bangalore        SME   Agent  2024-11-03 00:00:00    Yes
2031             9    Kolkata        SME  Mobile  2026-01-15 00:00:00    Yes
2032             8     Mumbai    Premium  Mobile  2022-11-30 00:00:00    Yes
2033             8       Pune        NaN  Mobile  2021-07-04 00:00:00     No
2034            10  hyderabad        SME  Mobile  2025-09-10 00:00:00     No
2035            12  Hyderabad     Retail   Agent  2021-07-10 00:00:00     No
2036             8     Mumbai  Corporate   Agent  2025-07-05 00:00:00    Yes
2037             8    Kolkata     Retail  Online  2022-10-17 00:00:00    Yes
2038             8  Bangalore     Retail   Agent  2023-08-26 00:00:00     No
2039             6    Chennai     Retail  Branch                  NaN    Yes

     Risk_Level  Monthly_Spend Transactions  Satisfaction_Score
2030       High       18815.18           58                 7.2
2031        Low       34300.44           83                 5.0
2032       High  not_available          147                 9.7
2033       High       10165.71           14                 6.4
2034       High       27227.44           85                 5.9
2035     Medium        8455.42          119                 8.6
2036       High       34087.69          134                 2.6
2037        Low       26518.74           87                 1.3
2038        Low       20943.11          107                 9.3
2039        Low       48511.32          119                 3.1

In [89]:
print(df.sample(10))

      Customer_ID  Age Annual_Income Account_Balance   Credit_Score  \
1311       100173   49         77307        44395.24            837
750        100032   39        165975       286209.94            343
930        101090   47        220113         79201.3            361
412        101611   40         43133        74850.92            765
242        100943  NaN         89309       224817.14  not_available
1781       101847   59         78909        37881.34            678
617        101798   25        112960        55035.72            796
536        100273   28           NaN       259020.23            344
803        101270   72         82804             NaN            407
801        100436   20        160720       142020.26            634

      Tenure_Years       City    Segment Channel            Join_Date Active  \
1311            11    Kolkata  Corporate  Online  2021-08-13 00:00:00    Yes
750              6      Delhi    Premium   Agent  2023-05-10 00:00:00     No
930              9       Pune    Premium   Agent  2024-06-03 00:00:00    Yes
412              3       Pune        SME  Online  2022-05-16 00:00:00    Yes
242              5      Delhi  Corporate  Branch  2021-10-05 00:00:00    Yes
1781            10     Mumbai     Retail  Mobile  2023-06-30 00:00:00     No
617              2  Hyderabad  Corporate  Online  2022-03-30 00:00:00     No
536              8    Chennai    Premium  Mobile  2025-03-27 00:00:00    Yes
803              4  Hyderabad    Premium  Online  2021-01-06 00:00:00    Yes
801              8    Kolkata  Corporate  Online  2024-10-14 00:00:00    Yes

     Risk_Level  Monthly_Spend Transactions  Satisfaction_Score
1311        Low       23565.35           75                 9.7
750        High       11089.18           41                 5.3
930        High  not_available           68                 3.0
412         Low        15207.3          129                 4.3
242        High       28656.53           88                 2.8
1781     Medium       48743.16          138                 6.6
617         Low       45607.85           74                 4.6
536        High        missing           91                 2.8
803        High       20861.64          110                 1.7
801      Medium       32161.03           92                 3.1

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [91]:
print(df.isnull().sum())

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [92]:
print("Duplicates:", df.duplicated().sum())

Duplicates: 40

In [93]:
df = df.drop_duplicates()

In [96]:
numeric_cols = ["Age", "Annual_Income", "Account_Balance","Credit_Score", "Tenure_Years","Monthly_Spend", "Transactions",
    "Satisfaction_Score"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [97]:
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [98]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df["Join_Date"] = df["Join_Date"].fillna(df["Join_Date"].median())

In [99]:
df["City"] = df["City"].replace({ "mumbai": "Mumbai","hyderabad": "Hyderabad","bangalore": "Bangalore","pune": "Pune",
    "delhi": "Delhi","kolkata": "Kolkata","chennai": "Chennai"})

In [100]:
df["Segment"] = df["Segment"].fillna(df["Segment"].mode()[0])

In [102]:
df["Active"] = df["Active"].replace({"Yes": "Yes","YES": "Yes","yes": "Yes","Y": "Yes","1": "Yes",
    1: "Yes","No": "No","NO": "No","no": "No","N": "No","0": "No",0: "No"})

In [103]:
df = df.rename(columns={"Annual_Income": "AnnualIncome","Account_Balance": "AccountBalance","Credit_Score": "CreditScore","Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate","Risk_Level": "RiskLevel","Monthly_Spend": "MonthlySpend","Satisfaction_Score": "SatisfactionScore"})

In [104]:
df = df.drop(columns=["Customer_ID"], errors="ignore")

In [105]:
df.dtypes

Age                         float64
AnnualIncome                float64
AccountBalance              float64
CreditScore                 float64
Tenure                        int64
City                         object
Segment                      object
Channel                      object
CustomerJoinDate     datetime64[ns]
Active                       object
RiskLevel                    object
MonthlySpend                float64
Transactions                float64
SatisfactionScore           float64
dtype: object

In [106]:
df.describe()

,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,CustomerJoinDate,MonthlySpend,Transactions,SatisfactionScore
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000,2000.000000,2000.00000,2000.000000
mean,47.006000,138362.001000,151577.633405,576.251500,7.574000,2023-08-23 23:16:47.999999744,24846.208835,75.46050,5.609200
min,18.000000,25163.000000,55.960000,300.000000,0.000000,2021-01-01 00:00:00,559.580000,1.00000,1.000000
25%,34.000000,88617.000000,83956.797500,434.000000,4.000000,2022-06-10 12:00:00,13115.135000,40.00000,3.600000
50%,47.000000,139914.000000,154119.265000,570.500000,8.000000,2023-08-24 00:00:00,24625.170000,76.00000,5.700000
75%,61.000000,188465.000000,219656.717500,720.250000,12.000000,2024-11-05 00:00:00,36337.937500,112.00000,7.700000
max,75.000000,249977.000000,299914.140000,850.000000,15.000000,2026-03-13 00:00:00,49942.820000,149.00000,10.000000
std,16.184991,61981.578361,82603.862653,160.930148,4.610548,NaN,13850.626971,42.57714,2.527554

In [107]:
df["City"].value_counts()

City
Mumbai       308
Hyderabad    292
Delhi        283
Kolkata      274
Pune         270
Bangalore    247
Chennai      246
Name: count, dtype: int64

In [108]:
df["Segment"].value_counts()

Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

In [109]:
df["Active"].value_counts()

Active
Yes    1345
No      597
Name: count, dtype: int64

In [110]:
df["RiskLevel"].value_counts()

RiskLevel
High      986
Low       540
Medium    474
Name: count, dtype: int64

In [122]:
# Q30 — Ultimate Pandas Cleaning Project
#You are a Data Scientist at a bank. Your raw customer dataset contains 2,000+ records with:
#• Missing values
#• Duplicate records
#• Invalid numerical values
#• Mixed datatypes
#• Invalid dates
#• Mixed date formats
#• Inconsistent categorical values
#• Binary text inconsistencies
#• Unnecessary identifier columns

df = pd.read_csv("C:\\Users\\DELL\\Downloads\\customer_analytics - customer_analytics.csv")
df = df.drop_duplicates()
numeric_cols = ["Age","Annual_Income","Account_Balance","Credit_Score","Tenure_Years","Monthly_Spend","Transactions",
    "Satisfaction_Score"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())
df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors="coerce")
df["Join_Date"] = df["Join_Date"].fillna(df["Join_Date"].median())
df["City"] = df["City"].replace({"mumbai": "Mumbai","hyderabad": "Hyderabad","bangalore": "Bangalore","pune": "Pune",
    "delhi": "Delhi","kolkata": "Kolkata","chennai": "Chennai"})
df["Segment"] = df["Segment"].fillna(df["Segment"].mode()[0])
df["Active"] = df["Active"].replace({"Yes": "Yes","YES": "Yes","yes": "Yes","Y": "Yes","1": "Yes",
    1: "Yes","No": "No","NO": "No","no": "No","N": "No","0": "No",0: "No"})
df = df.rename(columns={"Annual_Income": "AnnualIncome","Account_Balance": "AccountBalance","Credit_Score": "CreditScore","Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate","Risk_Level": "RiskLevel","Monthly_Spend": "MonthlySpend","Satisfaction_Score": "SatisfactionScore"})
df = df.drop(columns=["Customer_ID"], errors="ignore")
df["Income_Lakhs"] = df["AnnualIncome"] / 100000
df["MonthlyIncome"] = df["AnnualIncome"] / 12
df["Income_After_Spending"] = (df["MonthlyIncome"] - df["MonthlySpend"])
df["Balance_Income_Ratio"] = (df["AccountBalance"] /df["AnnualIncome"].replace(0, float("nan")))

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 2039
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    2000 non-null   float64
 1   AnnualIncome           2000 non-null   float64
 2   AccountBalance         2000 non-null   float64
 3   CreditScore            2000 non-null   float64
 4   Tenure                 2000 non-null   int64
 5   City                   1920 non-null   object
 6   Segment                2000 non-null   object
 7   Channel                2000 non-null   object
 8   CustomerJoinDate       2000 non-null   datetime64[ns]
 9   Active                 1942 non-null   object
 10  RiskLevel              2000 non-null   object
 11  MonthlySpend           2000 non-null   float64
 12  Transactions           2000 non-null   float64
 13  SatisfactionScore      2000 non-null   float64
 14  Income_Lakhs           2000 non-null   float64
 15  MonthlyIncome          2000 non-null   float64
 16  Income_After_Spending  2000 non-null   float64
 17  Balance_Income_Ratio   2000 non-null   float64
dtypes: datetime64[ns](1), float64(11), int64(1), object(5)
memory usage: 296.9+ KB

In [124]:
df.isnull().sum()

Age                       0
AnnualIncome              0
AccountBalance            0
CreditScore               0
Tenure                    0
City                     80
Segment                   0
Channel                   0
CustomerJoinDate          0
Active                   58
RiskLevel                 0
MonthlySpend              0
Transactions              0
SatisfactionScore         0
Income_Lakhs              0
MonthlyIncome             0
Income_After_Spending     0
Balance_Income_Ratio      0
dtype: int64

In [125]:
df.describe()

,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,CustomerJoinDate,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,47.006000,138362.001000,151577.633405,576.251500,7.574000,2023-08-23 23:16:47.999999744,24846.208835,75.46050,5.609200,1.383620,11530.166750,-13316.042085,1.497648
min,18.000000,25163.000000,55.960000,300.000000,0.000000,2021-01-01 00:00:00,559.580000,1.00000,1.000000,0.251630,2096.916667,-46902.986667,0.000281
25%,34.000000,88617.000000,83956.797500,434.000000,4.000000,2022-06-10 12:00:00,13115.135000,40.00000,3.600000,0.886170,7384.750000,-24603.837500,0.614241
50%,47.000000,139914.000000,154119.265000,570.500000,8.000000,2023-08-24 00:00:00,24625.170000,76.00000,5.700000,1.399140,11659.500000,-12917.411667,1.105980
75%,61.000000,188465.000000,219656.717500,720.250000,12.000000,2024-11-05 00:00:00,36337.937500,112.00000,7.700000,1.884650,15705.416667,-1793.519167,1.836354
max,75.000000,249977.000000,299914.140000,850.000000,15.000000,2026-03-13 00:00:00,49942.820000,149.00000,10.000000,2.499770,20831.416667,19642.133333,11.427467
std,16.184991,61981.578361,82603.862653,160.930148,4.610548,NaN,13850.626971,42.57714,2.527554,0.619816,5165.131530,14857.128756,1.451596

In [126]:
df.head(10)

,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135.0,3.1,0.44033,3669.416667,-19396.773333,2.528805
1,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106.0,8.2,2.15546,17962.166667,-6663.003333,1.180158
2,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146.0,6.3,2.26403,18866.916667,-9669.423333,0.706596
3,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115.0,9.7,0.87824,7318.666667,-5551.043333,3.367435
4,67.0,31570.0,242423.78,370.0,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94.0,3.7,0.31570,2630.833333,-31532.186667,7.678929
5,68.0,37087.0,180084.44,738.0,1,Chennai,Premium,Agent,2023-06-04,Yes,Low,15121.16,6.0,8.5,0.37087,3090.583333,-12030.576667,4.855730
6,47.0,67229.0,99629.81,464.0,4,Chennai,Retail,Online,2024-01-16,Yes,High,17655.61,31.0,2.8,0.67229,5602.416667,-12053.193333,1.481947
7,65.0,139914.0,61030.94,554.0,15,Kolkata,SME,Agent,2024-06-26,Yes,Medium,1720.85,139.0,9.7,1.39914,11659.500000,9938.650000,0.436203
8,63.0,153267.0,221707.97,508.0,5,Hyderabad,Premium,Mobile,2025-03-12,Yes,High,38043.07,76.0,7.1,1.53267,12772.250000,-25270.820000,1.446547
9,42.0,139914.0,41126.84,556.0,3,Kolkata,Corporate,Mobile,2021-10-07,Yes,Medium,11472.36,124.0,9.1,1.39914,11659.500000,187.140000,0.293944

In [132]:
df.to_csv("clean_data.csv")

In [133]:
df.to_csv(r"C:\Users\DELL\Downloads\clean_data.csv", index=False)